# 01-login.yml  → Solo hace login y muestra el token (seguro)
---
- name: 01 - Login a vCenter (solo prueba)
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Login y obtener token
      vmware.vmware_rest.vcenter_token:
        vcenter_hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
      register: vcenter_login
      no_log: true     # evita que aparezcan credenciales/token

    - name: Validar login exitoso
      fail:
        msg: "ERROR: No se pudo generar token desde vCenter"
      when: vcenter_login is failed

    - debug:
        msg: "Login OK → token válido por {{ vcenter_login.expires_in // 60 }} minutos"
