---
- name: 01 - Login a vCenter (solo prueba)
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Crear sesión en vCenter (nuevo módulo desde 3.0.0+)
      vmware.vmware_rest.vcenter_session:
        vcenter_hostname: "{{ vcenter_hostname }}"
        vcenter_username: "{{ vcenter_username }}"
        vcenter_password: "{{ vcenter_password }}"
        vcenter_validate_certs: false
      register: vcenter_login
      no_log: true

    - name: Validar que el login fue exitoso
      ansible.builtin.fail:
        msg: "ERROR: No se pudo autenticar contra vCenter {{ vcenter_hostname }}"
      when: vcenter_login is failed or vcenter_login.session_id is not defined

    - name: Calcular minutos restantes antes de la expiración del token
      set_fact:
        session_minutes: >-
          {{
            (
              (vcenter_login.expiry_time | to_datetime).timestamp() -
              (ansible_date_time.epoch | int)
            ) // 60
          }}

    - name: Mostrar información del token/sesión
      debug:
        msg: "Login OK → sesión válida por aproximadamente {{ session_minutes }} minutos"
