# 01-login.yml → Versión corregida y funcional en AAP 2.5 (vmware.vmware_rest 4.6.0)
---
- name: 01 - Login a vCenter (solo prueba)
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Crear sesión en vCenter (nuevo módulo desde 3.0.0+)
      vmware.vmware_rest.vcenter_session:
        vcenter_hostname: "{{ vcenter_hostname }}"
        vcenter_username: "{{ vcenter_username }}"
        vcenter_password: "{{ vcenter_password }}"
        vcenter_validate_certs: false
      register: vcenter_login
      no_log: true

    - name: Validar que el login fue exitoso
      fail:
        msg: "ERROR: No se pudo autenticar contra vCenter {{ vcenter_hostname }}"
      when: vcenter_login is failed or vcenter_login.session_id is not defined

    - name: Mostrar información del token/sesión
      debug:
        msg: >-
          Login OK → sesión válida por aproximadamente 
          {{ (vcenter_login.expires_at | default(0)) // 60 - (ansible_date_time.epoch | int) // 60 }} minutos
